import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from '@/components/AuthProvider';
import { Toaster } from 'react-hot-toast';
import { Rubik } from "next/font/google";
import SignInButton from '@/components/SignInButton';

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={rubik.className}>
      <body className="antialiased bg-white dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100">
        <Toaster
          position="top-right"
          toastOptions={{
            style: { background: "#1F1E24", color: "#fff", border: "1px solid rgba(255,255,255,0.08)" },
            success: { iconTheme: { primary: "#62C370", secondary: "#1F1E24" } },
            error: { iconTheme: { primary: "#E63946", secondary: "#1F1E24" } },
          }}
        />
        <AuthProvider>
          <header className="sticky top-0 z-40 bg-[#002D72] text-white">
            <div className="container-page flex items-center justify-between py-3">
              <div className="flex items-center gap-3">
                <div className="h-11 w-11 rounded-2xl bg-[#002D72] grid place-content-center text-black font-extrabold">
                  <span className="text-2xl">🍴</span>
                </div>
                <span className="text-xl font-semibold tracking-tight">Forkly</span>
              </div>
              <nav className="flex items-center gap-3">
                <a className="text-sm text-zinc-300 hover:text-white" href="/wishlist">
                  Wishlist
                </a>
                <SignInButton />
              </nav>
            </div>
          </header>

          <main className="container-page">{children}</main>

          <footer className="bg-[#002D72] text-white">
            <div className="container-page py-6 text-center text-sm">
              Made with 🍴 in NYC
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
